server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/hwang-won-ug/study/native-file-repo
        git:
#          uri: file:///Users/hwang-won-ug/study/git-local-repo
        uri: https://github.com/Hwangwonuk/spring-cloud-config.git
  profiles:
    default: native